[build]
# Comando para instalar las dependencias
install = "npm install"

# Comando para construir la aplicación
build = "npm run build"

# Comando para iniciar la aplicación
start = "npm run start"

[deploy]
# Imagen base para el despliegue
baseImage = "node:18"
